### ISSUE TITLE
How to handel png file?

### ISSUE THREAD

**Issue by yfliao** [yenchenlin/DeepLearningFlappyBird#21]
How to handle png file? I got the following message and have no idea how to solve it. I had tried to  install pil or pillow but didn't work.

$python deep_q_network.py
Traceback (most recent call last):
  File "deep_q_network.py", line 8, in <module>
    import wrapped_flappy_bird as game
  File "game/wrapped_flappy_bird.py", line 19, in <module>
    IMAGES, SOUNDS, HITMASKS = flappy_bird_utils.load()
  File "game/flappy_bird_utils.py", line 21, in load
    pygame.image.load('assets/sprites/0.png').convert_alpha(),
pygame.error: File is not a Windows BMP file

**Comment by ilovezhenzhen** [comment]
me too
pygame.error: File is not a Windows BMP file？？？
