### ISSUE TITLE
pygame.error: File is not a Windows BMP file？？？？？？？

### ISSUE THREAD

**Issue by ilovezhenzhen** [yenchenlin/DeepLearningFlappyBird#35]
Traceback (most recent call last):
  File "deep_q_network.py", line 8, in <module>
    import wrapped_flappy_bird as game
  File "game/wrapped_flappy_bird.py", line 19, in <module>
    IMAGES, SOUNDS, HITMASKS = flappy_bird_utils.load()
  File "game/flappy_bird_utils.py", line 21, in load
    pygame.image.load('assets/sprites/0.png').convert_alpha(),
pygame.error: File is not a Windows BMP file

**Comment by yenchenlin** [comment]
Sorry, I haven't tested it on Windows.

**Comment by ninoanthony** [comment]
I have same problem, can someone help me
