### ISSUE TITLE
parse_card: can't find card 0

### ISSUE THREAD

**Issue by lazywhite** [yenchenlin/DeepLearningFlappyBird#44]
```

Traceback (most recent call last):
  File "deep_q_network.py", line 8, in <module>
    import wrapped_flappy_bird as game
  File "game/wrapped_flappy_bird.py", line 19, in <module>
    IMAGES, SOUNDS, HITMASKS = flappy_bird_utils.load()
  File "game/flappy_bird_utils.py", line 42, in load
    SOUNDS['die']    = pygame.mixer.Sound('assets/audio/die' + soundExt)
MemoryError

```

**Comment by lazywhite** [comment]
I've solved this problem, I run this program on a server which doesn't have a sound card
use this command to get a fake sound card
```
modprobe snd_dummy
```
