### ISSUE TITLE
libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by ExcaliburAir** [yenchenlin/DeepLearningFlappyBird#46]
i want know whats wrong about this , THX very much.

libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "deep_q_network.py", line 215, in <module>
    main()
  File "deep_q_network.py", line 212, in main
    playGame()
  File "deep_q_network.py", line 209, in playGame
    trainNetwork(s, readout, h_fc1, sess)
  File "deep_q_network.py", line 82, in trainNetwork
    readout_action = tf.reduce_sum(tf.multiply(readout, a), reduction_indices=1)
AttributeError: 'module' object has no attribute 'multiply'

**Comment by ExcaliburAir** [comment]
"AttributeError: 'module' object has no attribute 'multiply'":
my tensorflow's version is too low that the 'multiply' must changed to 'mul'.
https://www.tensorflow.org/install/migration
