### ISSUE TITLE
Unable to open file 'assets/audio/die.ogg', please help >>. .<<

### ISSUE THREAD

**Issue by ouyangzhuzhu** [yenchenlin/DeepLearningFlappyBird#51]
[root@localhost DeepLearningFlappyBird]# python3.6 deep_q_network.py
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "deep_q_network.py", line 8, in <module>
    import wrapped_flappy_bird as game
  File "game/wrapped_flappy_bird.py", line 19, in <module>
    IMAGES, SOUNDS, HITMASKS = flappy_bird_utils.load()
  File "game/flappy_bird_utils.py", line 42, in load
    SOUNDS['die']    = pygame.mixer.Sound('assets/audio/die' + soundExt)
pygame.error: Unable to open file 'assets/audio/die.ogg'
[root@localhost DeepLearningFlappyBird]#

**Comment by BEMELON** [comment]
I also had the same error.
So I temporarily comment out some code and it works.
In  flappy_bird_utils.py  just comment out 41~45.

I hope there is a better solution.
